import {strict as assert} from 'node:assert';
let workers=0,requests=[];
globalThis.chrome={runtime:{getManifest:()=>({version:'1.8.8'}),sendMessage:async()=>{workers++;return {ok:false,error:'Unknown action'};}},storage:{local:{set:async()=>{}}}};
let response={ok:true,ads:true,family:false,exceptions:[],language:'en',version:'1.8.8'};
globalThis.fetch=async(url,options)=>{assert.equal(url,'https://maen.browser/api');requests.push(JSON.parse(options.body));return {ok:true,json:async()=>response};};
const {api}=await import('../assets/companion/api.js');
assert.equal((await api()).ads,true);
await api('save',{settings:{ads:false}});
assert.deepEqual(requests[1],{op:'save',settings:{ads:false}});
assert.equal(workers,0,'A stale worker must not control native protection requests');
response={ok:false,error:'Incorrect parent PIN.'};
await assert.rejects(api('save',{pin:'private-pin'}),e=>e.code==='E108');
const before=requests.length;
globalThis.fetch=async()=>{requests.push('failed');throw new Error('Network unavailable');};
await assert.rejects(api('save'),/PROTECTION_NETWORK/);
assert.equal(requests.length,before+1,'Failed writes must never be replayed');
globalThis.fetch=async()=>({ok:false,status:403});
await assert.rejects(api(),/PROTECTION_HTTP_403/);
globalThis.fetch=async()=>({ok:true,json:async()=>({ok:true})});
await assert.rejects(api(),/PROTECTION_RESPONSE/);
globalThis.fetch=async()=>({ok:true,json:async()=>({ok:true,ads:true,family:false,exceptions:[],language:'en'})});
chrome.storage.local.set=()=>new Promise(()=>{});
assert.equal((await api()).ads,true);
const {diagnosticCode,diagnosticReport,recordDiagnostic}=await import('../assets/companion/diagnostics.js');
assert.equal(diagnosticCode(new Error('Unknown action')),'E101');
assert.equal(diagnosticCode(new Error('Unknown operation')),'E106');
assert.equal(diagnosticCode({code:'PROTECTION_HTTP_403'}),'E103');
for(let n=0;n<30;n++)recordDiagnostic('get',new Error('private-pin https://private.example'));
const report=JSON.parse(diagnosticReport());
assert.equal(report.events.length,20);assert(!diagnosticReport().includes('private-pin'));assert(!diagnosticReport().includes('private.example'));
console.log('Direct native read/write bypasses stale Unknown action worker; no replay; diagnostics classified, bounded and private');
