#include "src/app/start_page.h"
#include <string>
#include "include/cef_parser.h"
namespace maenbrowser::ui {
std::string GetStartPageDataUrl() {
  static const char kHtml[] = R"HTML(<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MaenBrowser</title><style>
:root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Arial,sans-serif;background:linear-gradient(135deg,#f7f8ff,#eef3ff);color:#11182d;min-height:100vh;display:grid;place-items:center}.wrap{width:min(760px,90vw);text-align:center}.brand{font-size:42px;font-weight:750;letter-spacing:-1.5px}.mark{display:inline-grid;place-items:center;width:56px;height:56px;margin-right:12px;border-radius:18px;background:linear-gradient(135deg,#123cff,#7b4cff);color:white;font-weight:900;box-shadow:0 10px 30px #3048b733}.sub{color:#626b83;margin:10px 0 30px}.search{display:flex;background:white;border:1px solid #dfe4f0;border-radius:18px;padding:8px;box-shadow:0 12px 35px #34436a1a}.search input{flex:1;border:0;outline:0;font-size:17px;padding:13px 15px;background:transparent;color:#11182d}.search button{border:0;border-radius:13px;padding:0 22px;background:#263de8;color:white;font-weight:650;cursor:pointer}.links{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:22px}.links a{background:#ffffffcc;border:1px solid #e1e5ef;border-radius:16px;padding:18px 8px;text-decoration:none;color:#1b2440;font-weight:600}.foot{margin-top:28px;font-size:12px;color:#8991a5}@media(max-width:560px){.links{grid-template-columns:repeat(2,1fr)}.brand{font-size:34px}}@media(prefers-color-scheme:dark){body{background:linear-gradient(135deg,#101322,#151a30);color:#f5f7ff}.search,.links a{background:#1d2337;border-color:#303850;color:#f5f7ff}.search input{color:#f5f7ff}.sub,.foot{color:#aab1c5}}
</style></head><body><main class="wrap"><div class="brand"><span class="mark">M</span>MaenBrowser</div><div class="sub">Fast · Private · Lightweight</div><form class="search" action="https://www.google.com/search" method="get"><input name="q" autofocus autocomplete="off" placeholder="Search the web"><button>Search</button></form><div class="links"><a href="https://www.youtube.com/">YouTube</a><a href="https://web.whatsapp.com/">WhatsApp</a><a href="https://mail.google.com/">Gmail</a><a href="https://www.wikipedia.org/">Wikipedia</a></div><div class="foot">MaenBrowser · Local-first browsing</div></main></body></html>)HTML";
  return "data:text/html;charset=utf-8," + CefURIEncode(kHtml, false).ToString();
}
}
